/**
 * ═══════════════════════════════════════════════════════════════════════════════════════════════
 * FD-29 — A QR CODE THAT ACTUALLY SCANS, WITH NO DEPENDENCY AND NO NETWORK
 * ═══════════════════════════════════════════════════════════════════════════════════════════════
 *
 * The prescription sheet's footer carries a machine-readable copy of the visit number. Three
 * constraints decide that this file exists rather than an import:
 *
 *   1. **`apps/core` has no QR dependency and must not grow one for a footer.** The monorepo's only
 *      QR library is `qrcode.react` (`apps/web/package.json`), a React component that cannot run
 *      server-side. Adding a runtime dependency to the hospital's server image for one 16 mm square
 *      is a supply-chain cost with no offsetting benefit.
 *   2. **The document must be self-contained** — `RenderedDocument.html` is documented "inline CSS,
 *      no external fetch, no font CDN. The relay may be offline." So the code cannot be an
 *      `<img src>` to anywhere, and it cannot be drawn by client-side JS: the relay prints the HTML
 *      it is handed. `qrSvg` emits `<rect>` elements — no script, no fetch, no font.
 *   3. **`barField` above is the precedent for what NOT to do.** That helper is honestly labelled a
 *      *visual* bar field and says why: "shipping a bar-shaped picture that a scanner refuses is
 *      worse than shipping none." The artboard's own QR is exactly such a picture — a hand-drawn
 *      9 × 9 grid of `<div>`s. This file is the other answer to the same problem: a real encoder.
 *
 * ═══ THE SCOPE IS DELIBERATELY NARROW, AND IT REFUSES RATHER THAN DEGRADES ═══
 *
 * BYTE MODE, ERROR-CORRECTION LEVEL M, VERSIONS 1–10 (21 × 21 up to 57 × 57, 213 bytes). A visit
 * number is eleven characters. Numeric and alphanumeric modes would encode it more densely and buy
 * nothing at this size; levels L/Q/H would each need their own block table, and an unused table is
 * an untested one. `encodeQr` THROWS past 213 bytes rather than silently truncating — a QR that
 * scans as half a payload is the failure this whole file exists to avoid.
 *
 * ═══ HOW IT IS KNOWN TO BE CORRECT ═══
 *
 * Not by reading. `qr.test.ts` pins this encoder's output, module for module, against matrices
 * generated by `qrcode.react` — a different implementation by a different author — for payloads
 * that land on every one of versions 1 to 10, plus the exact payload this sheet prints. A QR that
 * two independent encoders agree on, bit for bit, is a QR a scanner reads.
 */

/** Byte-mode capacity in BYTES at level M, indexed by version − 1. */
const BYTE_CAPACITY_M: readonly number[] = [14, 26, 42, 62, 84, 106, 122, 152, 180, 213];

/**
 * Per version at level M: error-correction codewords per block, then the two block groups as
 * [count, data codewords each]. A version with one group leaves the second at zero.
 */
const BLOCKS_M: readonly (readonly [number, number, number, number, number])[] = [
  [10, 1, 16, 0, 0], [16, 1, 28, 0, 0], [26, 1, 44, 0, 0], [18, 2, 32, 0, 0], [24, 2, 43, 0, 0],
  [16, 4, 27, 0, 0], [18, 4, 31, 0, 0], [22, 2, 38, 2, 39], [22, 3, 36, 2, 37], [26, 4, 43, 1, 44],
];

/** Alignment-pattern centre coordinates per version. Version 1 has none. */
const ALIGNMENT_CENTRES: readonly (readonly number[])[] = [
  [], [6, 18], [6, 22], [6, 26], [6, 30], [6, 34],
  [6, 22, 38], [6, 24, 42], [6, 26, 46], [6, 28, 50],
];

/** GF(256) under the QR primitive polynomial x⁸ + x⁴ + x³ + x² + 1 (0x11D). */
const GF_EXP = new Uint8Array(512);
const GF_LOG = new Uint8Array(256);
{
  let x = 1;
  for (let i = 0; i < 255; i += 1) {
    GF_EXP[i] = x;
    GF_LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i += 1) GF_EXP[i] = GF_EXP[i - 255]!;
}

function gfMul(a: number, b: number): number {
  if (a === 0 || b === 0) return 0;
  return GF_EXP[GF_LOG[a]! + GF_LOG[b]!]!;
}

/** The Reed–Solomon generator polynomial of the given degree, coefficients high-order first. */
function generatorPoly(degree: number): number[] {
  let poly = [1];
  for (let i = 0; i < degree; i += 1) {
    const next = new Array<number>(poly.length + 1).fill(0);
    for (let j = 0; j < poly.length; j += 1) {
      next[j] = (next[j] ?? 0) ^ gfMul(poly[j]!, 1);
      next[j + 1] = (next[j + 1] ?? 0) ^ gfMul(poly[j]!, GF_EXP[i]!);
    }
    poly = next;
  }
  return poly;
}

/** The EC codewords for one data block: the remainder of the block divided by the generator. */
function ecCodewords(data: readonly number[], count: number): number[] {
  const gen = generatorPoly(count);
  const rem = new Array<number>(count).fill(0);
  for (const byte of data) {
    const factor = byte ^ rem[0]!;
    rem.shift();
    rem.push(0);
    for (let i = 0; i < count; i += 1) rem[i] = rem[i]! ^ gfMul(gen[i + 1]!, factor);
  }
  return rem;
}

/** A bit sink, most-significant bit first — the order every QR field is written in. */
class Bits {
  readonly bits: number[] = [];
  push(value: number, length: number): void {
    for (let i = length - 1; i >= 0; i -= 1) this.bits.push((value >>> i) & 1);
  }
}

/**
 * The eight mask conditions, by pattern number. A module is inverted where its condition holds.
 * Spelled out rather than derived: the arithmetic in patterns 4–7 is where an off-by-one hides.
 */
const MASKS: readonly ((row: number, col: number) => boolean)[] = [
  (r, c) => (r + c) % 2 === 0,
  (r) => r % 2 === 0,
  (_r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
];

type Grid = { readonly size: number; readonly dark: boolean[][]; readonly fixed: boolean[][] };

function blankGrid(size: number): Grid {
  return {
    size,
    dark: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
    fixed: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
  };
}

function set(g: Grid, row: number, col: number, dark: boolean): void {
  g.dark[row]![col] = dark;
  g.fixed[row]![col] = true;
}

/** Finder pattern plus its one-module separator, anchored at the given top-left of the 7 × 7. */
function drawFinder(g: Grid, top: number, left: number): void {
  for (let r = -1; r <= 7; r += 1) {
    for (let c = -1; c <= 7; c += 1) {
      const row = top + r;
      const col = left + c;
      if (row < 0 || row >= g.size || col < 0 || col >= g.size) continue;
      const ring = r >= 0 && r <= 6 && c >= 0 && c <= 6
        && (r === 0 || r === 6 || c === 0 || c === 6 || (r >= 2 && r <= 4 && c >= 2 && c <= 4));
      set(g, row, col, ring);
    }
  }
}

function drawFunctionPatterns(g: Grid, version: number): void {
  const last = g.size - 1;
  drawFinder(g, 0, 0);
  drawFinder(g, 0, last - 6);
  drawFinder(g, last - 6, 0);

  // Timing patterns — row 6 and column 6, alternating from the finders inward.
  for (let i = 8; i < last - 7; i += 1) {
    set(g, 6, i, i % 2 === 0);
    set(g, i, 6, i % 2 === 0);
  }

  // Alignment patterns, at every pairing of the version's centres except the three finder corners.
  const centres = ALIGNMENT_CENTRES[version - 1]!;
  for (const cr of centres) {
    for (const cc of centres) {
      const atFinder = (cr === 6 && cc === 6) || (cr === 6 && cc === last - 6) || (cr === last - 6 && cc === 6);
      if (atFinder) continue;
      for (let r = -2; r <= 2; r += 1) {
        for (let c = -2; c <= 2; c += 1) {
          set(g, cr + r, cc + c, Math.max(Math.abs(r), Math.abs(c)) !== 1);
        }
      }
    }
  }

  // Reserve the format-information areas so data placement skips them. The dark module at
  // (4 × version + 9, 8) falls inside the second copy's vertical arm and is re-asserted by
  // `drawFormat` AFTER the bits are written — reserving it here only keeps data out.
  for (let i = 0; i <= 8; i += 1) {
    if (i !== 6) {
      set(g, 8, i, false);
      set(g, i, 8, false);
    }
  }
  for (let i = 0; i < 8; i += 1) {
    set(g, 8, last - i, false);
    set(g, last - i, 8, false);
  }

  // Version information (versions 7 and up), reserved here and written after masking.
  if (version >= 7) {
    for (let i = 0; i < 18; i += 1) {
      const a = Math.floor(i / 3);
      const b = (i % 3) + last - 10;
      set(g, a, b, false);
      set(g, b, a, false);
    }
  }
}

/** BCH(15,5) format information: five bits of level+mask, ten of remainder, XOR-ed with 0x5412. */
function formatBits(maskPattern: number): number {
  // Level M is `00`; the level bits lead the mask bits.
  const data = maskPattern;
  let rem = data << 10;
  for (let i = 4; i >= 0; i -= 1) {
    if ((rem >>> (i + 10)) & 1) rem ^= 0x537 << i;
  }
  return ((data << 10) | rem) ^ 0x5412;
}

/** BCH(18,6) version information, for versions 7 and up. */
function versionBits(version: number): number {
  let rem = version << 12;
  for (let i = 5; i >= 0; i -= 1) {
    if ((rem >>> (i + 12)) & 1) rem ^= 0x1f25 << i;
  }
  return (version << 12) | rem;
}

function drawFormat(g: Grid, maskPattern: number): void {
  const bits = formatBits(maskPattern);
  const last = g.size - 1;
  for (let i = 0; i < 15; i += 1) {
    // MOST-SIGNIFICANT BIT FIRST, and this is the one place the convention is easy to invert:
    // the leading bit of the 15-bit word goes at (8,0), not the trailing one. Getting it backwards
    // leaves eight modules wrong out of 441 — a code that still looks like a QR and scans as
    // nothing. `qr.test.ts` pins it against an independent encoder for exactly that reason.
    const on = ((bits >>> (14 - i)) & 1) === 1;
    // The copy beside the top-left finder, wrapping around its corner.
    if (i < 6) g.dark[8]![i] = on;
    else if (i === 6) g.dark[8]![7] = on;
    else if (i === 7) g.dark[8]![8] = on;
    else if (i === 8) g.dark[7]![8] = on;
    else g.dark[14 - i]![8] = on;
    // The split copy beside the other two finders: SEVEN modules up the bottom-left finder, then
    // EIGHT across the top-right. Splitting it 8/7 instead leaves (8, size−8) unwritten and puts a
    // format bit under the always-dark module — one wrong module, and the code stops scanning.
    if (i < 7) g.dark[last - i]![8] = on;
    else g.dark[8]![last - 14 + i] = on;
  }
  // Always dark, and written LAST because it sits on top of the second copy's eighth position.
  g.dark[last - 7]![8] = true;
}

function drawVersion(g: Grid, version: number): void {
  if (version < 7) return;
  const bits = versionBits(version);
  const last = g.size - 1;
  for (let i = 0; i < 18; i += 1) {
    const on = ((bits >>> i) & 1) === 1;
    const a = Math.floor(i / 3);
    const b = (i % 3) + last - 10;
    g.dark[a]![b] = on;
    g.dark[b]![a] = on;
  }
}

/**
 * The four penalty rules of the standard, summed. Lower is a better mask.
 *
 * ═══ RULE 3 IS SCALE-INVARIANT, AND THAT IS THE TRAP ═══
 *
 * The finder-lookalike rule is written in the standard as a RATIO — dark:light:dark:light:dark of
 * 1:1:3:1:1 — not as the literal seven modules `1011101`. A doubled run (`1100111111001 1`) is the
 * same ratio and penalises the same. A first cut of this file matched only the 1× case, agreed with
 * the reference encoder on most symbols, and picked a different mask on roughly a third of them.
 * Since the mask number is itself encoded in the format bits, a wrong choice is not merely
 * suboptimal — it produces a DIFFERENT symbol, which is why this is pinned rather than reasoned about.
 *
 * The run-history form below is the standard's own: six run lengths ending at the current position,
 * with the area outside the symbol counted as a light run so a lookalike hard against the edge
 * still scores, and one count for EACH side that has four-times-the-unit of quiet.
 */
function penalty(g: Grid): number {
  const n = g.size;
  let score = 0;

  const scoreLine = (line: readonly boolean[]): number => {
    let total = 0;
    let runColor = false;
    let runLength = 0;
    const history = [0, 0, 0, 0, 0, 0, 0];

    const addHistory = (length: number): void => {
      // A zero at the head means nothing has been recorded yet, so this is the first run and the
      // light border outside the symbol joins it.
      history.pop();
      history.unshift(history[0] === 0 ? length + n : length);
    };
    const countPatterns = (): number => {
      const unit = history[1]!;
      const core = unit > 0 && history[2] === unit && history[3] === unit * 3
        && history[4] === unit && history[5] === unit;
      if (!core) return 0;
      return (history[0]! >= unit * 4 && history[6]! >= unit ? 1 : 0)
        + (history[6]! >= unit * 4 && history[0]! >= unit ? 1 : 0);
    };

    for (let i = 0; i < n; i += 1) {
      if (line[i] === runColor) {
        runLength += 1;
        if (runLength === 5) total += 3;
        else if (runLength > 5) total += 1;
        continue;
      }
      addHistory(runLength);
      if (!runColor) total += countPatterns() * 40;
      runColor = line[i]!;
      runLength = 1;
    }
    if (runColor) {
      addHistory(runLength);
      runLength = 0;
    }
    addHistory(runLength + n); // the light border after the last run
    return total + countPatterns() * 40;
  };

  for (let r = 0; r < n; r += 1) score += scoreLine(g.dark[r]!);
  for (let c = 0; c < n; c += 1) score += scoreLine(g.dark.map((row) => row[c]!));

  for (let r = 0; r < n - 1; r += 1) {
    for (let c = 0; c < n - 1; c += 1) {
      const v = g.dark[r]![c];
      if (v === g.dark[r]![c + 1] && v === g.dark[r + 1]![c] && v === g.dark[r + 1]![c + 1]) score += 3;
    }
  }

  // Deviation from a half-dark symbol, in 5-percentage-point steps. Written as the standard's
  // integer form rather than `floor(|percent − 50| / 5)`: the two differ by one step whenever the
  // ratio lands exactly on a multiple of five, which is often enough to pick a different mask.
  let darkCount = 0;
  for (let r = 0; r < n; r += 1) for (let c = 0; c < n; c += 1) if (g.dark[r]![c]) darkCount += 1;
  const total = n * n;
  score += (Math.ceil(Math.abs(darkCount * 20 - total * 10) / total) - 1) * 10;

  return score;
}

/**
 * Encode a payload as a QR matrix — `true` is a dark module. Byte mode, level M.
 *
 * @throws if the UTF-8 payload exceeds 213 bytes (version 10 at level M).
 */
export function encodeQr(payload: string): boolean[][] {
  return encodeQrMasked(payload, null);
}

/**
 * The same encoder with the mask FORCED, which is the seam `qr.test.ts` needs.
 *
 * Mask selection and module placement fail in ways that look identical from the outside — both
 * yield a matrix of the right size that scans as nothing. Pinning the eight forced masks separately
 * says which of the two is broken when a fixture goes red, instead of leaving a reader to guess.
 *
 * @param maskPattern 0–7 to force, or `null` to score all eight and keep the best.
 */
export function encodeQrMasked(payload: string, maskPattern: number | null): boolean[][] {
  const data = Array.from(new TextEncoder().encode(payload));
  const version = BYTE_CAPACITY_M.findIndex((cap) => data.length <= cap) + 1;
  if (version === 0) {
    throw new Error(`qr payload of ${String(data.length)} bytes exceeds the 213-byte level-M ceiling`);
  }

  const [ecPerBlock, g1Count, g1Data, g2Count, g2Data] = BLOCKS_M[version - 1]!;
  const totalData = g1Count * g1Data + g2Count * g2Data;

  const bits = new Bits();
  bits.push(0b0100, 4); // byte mode
  bits.push(data.length, version >= 10 ? 16 : 8);
  for (const byte of data) bits.push(byte, 8);
  // Terminator, then pad to a byte boundary, then the standard alternating pad codewords.
  bits.push(0, Math.min(4, totalData * 8 - bits.bits.length));
  while (bits.bits.length % 8 !== 0) bits.bits.push(0);
  const codewords: number[] = [];
  for (let i = 0; i < bits.bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j += 1) byte = (byte << 1) | bits.bits[i + j]!;
    codewords.push(byte);
  }
  for (let i = 0; codewords.length < totalData; i += 1) codewords.push(i % 2 === 0 ? 0xec : 0x11);

  // Split into blocks, compute each block's EC, then interleave — data first, then EC.
  const dataBlocks: number[][] = [];
  const ecBlocks: number[][] = [];
  let cursor = 0;
  for (const [count, size] of [[g1Count, g1Data], [g2Count, g2Data]] as const) {
    for (let b = 0; b < count; b += 1) {
      const block = codewords.slice(cursor, cursor + size);
      cursor += size;
      dataBlocks.push(block);
      ecBlocks.push(ecCodewords(block, ecPerBlock));
    }
  }
  const interleaved: number[] = [];
  for (let i = 0; i < Math.max(g1Data, g2Data); i += 1) {
    for (const block of dataBlocks) if (i < block.length) interleaved.push(block[i]!);
  }
  for (let i = 0; i < ecPerBlock; i += 1) {
    for (const block of ecBlocks) interleaved.push(block[i]!);
  }

  const size = version * 4 + 17;
  const grid = blankGrid(size);
  drawFunctionPatterns(grid, version);

  // The zigzag: two columns at a time from the right, skipping the vertical timing column.
  const stream: number[] = [];
  for (const byte of interleaved) for (let i = 7; i >= 0; i -= 1) stream.push((byte >>> i) & 1);
  /*
    NO REMAINDER-BIT PADDING, and its absence is deliberate rather than forgotten. Versions 2-6
    leave seven unused bits after the last codeword and the standard fills them with ZERO. A table
    of them was written here first, and a mutation run proved it could not matter: the placement
    loop below writes `at < stream.length && stream[at] === 1`, so a position past the end of the
    stream is already dark = false, which IS the zero. Pushing the zeros and not pushing them
    produced identical matrices for all 4,000 payloads tried. Dead code that looks load-bearing is
    worse than no code, so it is gone and this is why.
  */
  let at = 0;
  let upward = true;
  let right = size - 1;
  while (right >= 1) {
    if (right === 6) right = 5; // column 6 is the vertical timing pattern — the pair steps past it
    for (let step = 0; step < size; step += 1) {
      const row = upward ? size - 1 - step : step;
      for (const col of [right, right - 1]) {
        if (grid.fixed[row]![col]) continue;
        grid.dark[row]![col] = at < stream.length && stream[at] === 1;
        at += 1;
      }
    }
    upward = !upward;
    right -= 2;
  }

  // Mask, score, keep the best. The format bits differ per mask, so they are written inside the loop.
  let best: boolean[][] | null = null;
  let bestScore = Number.POSITIVE_INFINITY;
  const unmasked = grid.dark.map((row) => [...row]);
  for (let m = maskPattern ?? 0; m < (maskPattern === null ? 8 : maskPattern + 1); m += 1) {
    const condition = MASKS[m]!;
    for (let r = 0; r < size; r += 1) {
      for (let c = 0; c < size; c += 1) {
        grid.dark[r]![c] = grid.fixed[r]![c] ? unmasked[r]![c]! : unmasked[r]![c]! !== condition(r, c);
      }
    }
    drawFormat(grid, m);
    drawVersion(grid, version);
    const score = penalty(grid);
    if (score < bestScore) {
      bestScore = score;
      best = grid.dark.map((row) => [...row]);
    }
  }
  return best!;
}

/**
 * The matrix as an inline SVG of black rectangles — no script, no fetch, no font.
 *
 * `shape-rendering="crispEdges"` matters on paper: without it a printer's antialiasing softens
 * module edges at 16 mm and a phone camera starts refusing the code.
 */
export function qrSvg(payload: string, sizePx: number, quietModules = 2): string {
  const matrix = encodeQr(payload);
  const n = matrix.length + quietModules * 2;
  const rects: string[] = [];
  for (let r = 0; r < matrix.length; r += 1) {
    // One rect per horizontal run rather than per module — a third of the bytes, same picture.
    let runStart = -1;
    for (let c = 0; c <= matrix[r]!.length; c += 1) {
      const on = c < matrix[r]!.length && matrix[r]![c] === true;
      if (on && runStart === -1) runStart = c;
      if (!on && runStart !== -1) {
        rects.push(`<rect x="${String(runStart + quietModules)}" y="${String(r + quietModules)}" width="${String(c - runStart)}" height="1"/>`);
        runStart = -1;
      }
    }
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${String(sizePx)}" height="${String(sizePx)}" viewBox="0 0 ${String(n)} ${String(n)}" shape-rendering="crispEdges" role="img" aria-label="visit number"><rect width="${String(n)}" height="${String(n)}" fill="#fff"/><g fill="#000">${rects.join("")}</g></svg>`;
}
